spring:
  application:
    name: pharmacy
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pharmacy
    username: root
    password: Hunter@4343
  jpa:
    show_sql: true
    properties:
      show-sql: true
      hibernate:
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: techtips753@gmail.com
    password: sorv ybgj sgdx dzcx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  file:
    name: logs/app.log
  level:
    root: DEBUG

server:
  port: 8091
